### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [colinr23/stampr#1]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

`stampr` imports 'rgeos', 'rgdal', 'maptools' using maptools::unionSpatialPolygons rgeos::gArea rgeos::gBuffer rgeos::gCentroid rgeos::gConvexHull rgeos::gDifference rgeos::gDistance rgeos::gEnvelope rgeos::gIntersection rgeos::gIntersects rgeos::gLength rgeos::gSimplify rgeos::gUnaryUnion as found by `pkgapi`, bulk imports in NAMESPACE. From https://r-spatial.org/r/2023/04/10/evolution3.html and https://github.com/r-spatial/evolution/blob/main/pkgapi_230305_refs.csv, probably `sf` is the best match, using coercion to and from `sp` classes. With `sf`, you need to be aware that GEOS is only used for planar geometries, so either turn off `s2` or enforce planar geometries to get the same GEOS algorithms as in `rgeos`. Please fix best by June, latest October 2023.

**Comment by thomasgaquiere** [comment]
Hello !

For my research purposes (Spatio-temporal analysis of moving canopy gaps polygons), I used the stampR package, 

I decided to 'rebuild' the stamp function in stampR  (stamp_sf function on my fork) (in fact : change rgeos functions to sf functions (and dealing with some issues from the sf::st_intersection function) and add parallelization to deal with large datasets), 

@colinr23, even if actually only the main function of the package has been rebuilt, I'm really interested in patching the rest of the packages' functions (+ update Namespace and documentation)

If you're interested, we can get into details by email,

**Comment by rsbivand** [comment]
It also looks as though @jedalong 's fork tas also moved towards `sf`, so working in collaboration sounds very promising.

**Comment by jedalong** [comment]
Thanks for raising this @rsbivand. Yes i have tried to rewrite entirely in sf (i think i am pretty much there but worth some checks) but we have been slow in moving to CRAN because i am in process of taking over maintainer from Colin.  I have emailed CRAN with no response, so I will just update and make a note that I am taking over. 

@thomasgaquiere I will reach out via email for more details. But a simple suggestion from me would be for me to update current functionality with my version (assuming my updates pass tests and are sufficient) then in a subsequent update we can add in your improvements!

**Comment by rsbivand** [comment]
4.3.0 was released today, so CRAN have been very busy. Was it Colin who emailed to nominate you?

**Comment by jedalong** [comment]
yeah it was colin who emailed and it was back at the end of March that he emailed, but I will try and go ahead with an update next week and see if they kick it back to us. Thanks!

**Comment by rsbivand** [comment]
Maybe refer to the email with date in the submission note?

**Comment by colinr23** [comment]
Hi all, happy to support @jedalong in taking over as maintainer and integration of improvements from @thomasgaquiere - don't have time to contribute much these days.. Jed we can coordinate over email if I need to send another nudge to move things along

**Comment by rsbivand** [comment]
Thanks for your cooperation!
